name: Windows, MinGW

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  MinGW-Build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Install MinGW
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          mingw-w64-${{ matrix.env }}-toolchain
          base-devel
          git

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Build
      run: make lib
